# Generated by Django 5.0.4 on 2024-05-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('kerberosID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('uniqueiitdid', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('deviceUUID', models.CharField(max_length=50)),
            ],
        ),
    ]
