# Generated by Django 5.0.4 on 2024-05-02 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kerberos_profiles', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academicYear', models.CharField(max_length=10)),
                ('semesterNumber', models.IntegerField(default=0)),
                ('startDate', models.DateField(default=None)),
                ('endDate', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseCode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=100)),
                ('numberOfClasses', models.IntegerField(default=0)),
                ('courseInstructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kerberos_profiles.profile')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.semester')),
            ],
        ),
        migrations.CreateModel(
            name='CourseClassDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classDate', models.DateField(default=None)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.course')),
            ],
        ),
        migrations.AddConstraint(
            model_name='courseclassdates',
            constraint=models.UniqueConstraint(fields=('course', 'classDate'), name='unique_class_date'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('courseCode', 'semester'), name='unique_course'),
        ),
    ]
