# Generated by Django 5.0.4 on 2024-05-02 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('kerberos_profiles', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAttendanceKey',
            fields=[
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='curriculum.course')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('privateKey', models.TextField()),
                ('publicKey', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None)),
                ('time', models.TimeField(default=None)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kerberos_profiles.profile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('student', 'course', 'date'), name='unique_attendance'),
        ),
    ]
